### ISSUE TITLE
Emacs compilation fails on macOS 10.14.6 with Xcode11

### ISSUE THREAD

**Issue by daviderestivo** [daviderestivo/homebrew-emacs-head#15]
Since the release of Xcode 11, Emacs (HEAD) fails to compile on macOS (10.14.6). It still correctly compiles with the previous version of Xcode (10.3). The error message is:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../lisp update-subdirs
cp -f temacs bootstrap-emacs
rm -f bootstrap-emacs.pdmp
./temacs --batch  -l loadup --temacs=pbootstrap
dyld: lazy symbol binding failed: Symbol not found: _aligned_alloc
  Referenced from: /private/tmp/emacs-head-20190921-27889-1s1yk6s/src/./temacs
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _aligned_alloc
  Referenced from: /private/tmp/emacs-head-20190921-27889-1s1yk6s/src/./temacs
  Expected in: /usr/lib/libSystem.B.dylib

make[1]: *** [bootstrap-emacs.pdmp] Abort trap: 6
make: *** [src] Error 2
make: *** Waiting for unfinished jobs....
```

I've posted a message in [reddit](https://www.reddit.com/r/emacs/comments/d7eu9i/emacs_compilation_fails_on_macos_10146_with/) to see if someone else have a solution for this issue.

**Comment by daviderestivo** [comment]
Related [bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36172). No solution so far.

**Comment by gdonald** [comment]
Same errors here.  Same versions as well: Mac OS v10.14.6 with Xcode11.  `sudo xcode-select -s /Applications/Xcode.app` did not help.

**Comment by idcrook** [comment]
There might? be a build workaround referenced here:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36356#14

```
When I disable _aligned_alloc in config.h, I get the _freea failure:
```

where the `_freea` failure was [patched](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36356#17):

`Paul's commit 848ff94b45 on master has fixed this for me.`

**Comment by daviderestivo** [comment]
> ```
> When I disable _aligned_alloc in config.h, I get the _freea failure:
> ```

I'm gonna try to see if I can do this within the formula. Thanks 👍

**Comment by daviderestivo** [comment]
@idcrook Fixed in 290f291. Thanks a lot.
